# Generated by Django 3.1.3 on 2020-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('city', models.CharField(default='', editable=False, max_length=20)),
                ('category', models.CharField(default='', editable=False, max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
